## **Part B: Dataset Understanding & Preparation**

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('dataset/students_dataset.csv')

In [3]:
data.columns

Index(['student_id', 'age', 'country_region', 'device_type',
       'education_background', 'course_level', 'course_category',
       'course_start_date', 'week_of_year', 'sessions', 'time_spent_hours',
       'videos_watched', 'quiz_attempts', 'assignments_submitted',
       'forum_posts', 'avg_quiz_score', 'attendance_rate', 'completion_status',
       'final_score'],
      dtype='object')

### Task 6: Feature & Target Identification

In [4]:
X = data.drop(columns=['student_id','age','device_type','course_start_date'])

In [5]:
y_cls = data.completion_status

In [6]:
y_reg = data.final_score

### Tasl 8: Data Preprocessing

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
# data before preprocessing
X.head()

,country_region,education_background,course_level,course_category,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,Europe,Undergrad,Intermediate,Business,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,Europe,Undergrad,Intermediate,Programming,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,Europe,Graduate,Advanced,Programming,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,Asia,Undergrad,Beginner,Design,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,Asia,WorkingPro,Advanced,Business,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

In [9]:
# Cheacking missing values
X.isna().sum()

country_region             0
education_background       0
course_level               0
course_category            0
week_of_year               0
sessions                   0
time_spent_hours         112
videos_watched             0
quiz_attempts              0
assignments_submitted      0
forum_posts                0
avg_quiz_score            81
attendance_rate           80
completion_status          0
final_score                0
dtype: int64

In [10]:
# Filling missing values with 0
X.fillna(0,inplace=True)

In [11]:
# Cheacking Datatypes
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country_region         5200 non-null   object
 1   education_background   5200 non-null   object
 2   course_level           5200 non-null   object
 3   course_category        5200 non-null   object
 4   week_of_year           5200 non-null   int64
 5   sessions               5200 non-null   int64
 6   time_spent_hours       5200 non-null   float64
 7   videos_watched         5200 non-null   int64
 8   quiz_attempts          5200 non-null   int64
 9   assignments_submitted  5200 non-null   int64
 10  forum_posts            5200 non-null   int64
 11  avg_quiz_score         5200 non-null   float64
 12  attendance_rate        5200 non-null   float64
 13  completion_status      5200 non-null   int64
 14  final_score            5200 non-null   float64
dtypes: float64(4), int64(7), object(4)
memory usage: 609.5+ KB

In [12]:
# Making variables for Encoder with and without order

education = ['HighSchool','Undergrad','Graduate','WorkingPro']
course_lvl = ['Beginner','Intermediate','Advanced']
country = X['country_region'].unique()
course_cat = X['course_category'].unique()

In [13]:
# Using Ordinal Encoder for Encoding Categorical features
OE = OrdinalEncoder(
    categories=[education,course_lvl,country,course_cat]
)

In [14]:
# Replacing values to categorical to numeric
X[['education_background','course_level','country_region','course_category']] = OE.fit_transform(X[['education_background','course_level','country_region','course_category']])

In [15]:
# Data Overview after Preprocessing
X.head()

,country_region,education_background,course_level,course_category,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,0.0,1.0,1.0,0.0,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,0.0,1.0,1.0,1.0,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,0.0,2.0,2.0,1.0,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,1.0,1.0,0.0,2.0,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,1.0,3.0,2.0,0.0,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

### Task 7: Train-Test Split

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
# Train-Test-Split for Regression 
X_train_reg,X_test_reg,y_train_reg,y_test_reg = train_test_split(X,y_reg,test_size=0.2,random_state=42)

In [18]:
# Train-Test-Split for Classification 
X_train_cls,X_test_cls,y_train_cls,y_test_cls = train_test_split(X,y_cls,test_size=0.2,random_state=42)

## **Part C: Bagging (Bootstrap Aggregation)**

In [19]:
from sklearn.ensemble import BaggingClassifier,BaggingRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

### Task: 9: Train a Bagging Classifier

In [20]:
bag_cls = BaggingClassifier(random_state=42)

In [21]:
# model training
bag_cls.fit(X_train_cls,y_train_cls)

BaggingClassifier(random_state=42)

### Task 10: Train a Bagging Regressor

In [22]:
bag_reg = BaggingRegressor(random_state=42)

In [23]:
# model training
bag_reg.fit(X_train_reg,y_train_reg)

BaggingRegressor(random_state=42)

### Task 11: Compare bagging results with a single base model

In [24]:
# creating model with parameters to prevent overfitting
tree_reg = DecisionTreeRegressor(max_depth=5, min_samples_split=2, random_state=42)
tree_cls = DecisionTreeClassifier(max_depth=5, min_samples_split=2, random_state=42)

In [25]:
# training regression model
tree_reg.fit(X_train_reg,y_train_reg)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [26]:
# training classification model
tree_cls.fit(X_train_cls,y_train_cls)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [27]:
# Regressor model
bag_pred_reg = bag_reg.predict(X_test_reg)
tree_pred_reg = tree_reg.predict(X_test_reg)

In [28]:
# Classification model
bag_pred_cls = bag_cls.predict(X_test_cls)
tree_pred_cls = tree_cls.predict(X_test_cls)

In [29]:
from sklearn.metrics import accuracy_score,r2_score

In [30]:
pd.DataFrame({
    'R2 Score': [r2_score(y_test_reg,tree_pred_reg),r2_score(y_test_reg,bag_pred_reg)],
    'Accuracy Score': [r2_score(y_test_cls,tree_pred_cls),r2_score(y_test_cls,bag_pred_cls)]
},index=['Decision Tree','Bagging Model'])

               R2 Score  Accuracy Score
Decision Tree  0.998326             1.0
Bagging Model  0.999979             1.0

**Observation:**

Bagging classifier achieved the same accuracy (1.0) as the base model, indicating no significant improvement. However, bagging regressor showed a slight improvement over the base model.

**Conclusion:**

This suggests that the base model already performs very well, and bagging mainly helped in reducing variance for regression but had minimal impact on classification.

## **Part D: Boosting Algorithms**

### **AdaBoost**

In [31]:
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor

#### Task 12: Implement AdaBoost Classifier

In [32]:
ada_cls = AdaBoostClassifier(n_estimators=100,learning_rate=0.2,random_state=42)

In [33]:
ada_cls.fit(X_train_cls,y_train_cls)

AdaBoostClassifier(learning_rate=0.2, n_estimators=100, random_state=42)

In [34]:
ada_pred_cls = ada_cls.predict(X_test_cls)

#### Task 13: Implement AdaBoost Regressor

In [35]:
ada_reg = AdaBoostRegressor(n_estimators=100,learning_rate=0.2,random_state=42)

In [36]:
ada_reg.fit(X_train_reg,y_train_reg)

AdaBoostRegressor(learning_rate=0.2, n_estimators=100, random_state=42)

In [37]:
ada_pred_reg = ada_reg.predict(X_train_reg)

#### Task 14: Analyze how weak learners improve sequentially

AdaBoost improves model performance by training weak learners sequentially, where each new model focuses more on the samples that were misclassified by previous models. It assigns higher weights to incorrectly predicted instances, forcing the next learner to pay more attention to difficult cases.

As the sequence progresses, the model gradually reduces errors by combining all weak learners into a strong final model using weighted voting. This step-by-step correction helps in reducing bias and improving overall accuracy.

### **Gradient Boosting**

In [38]:
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier

#### Task 15: Implement Gradient Boosting Classifier

In [39]:
gbm_cls = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42)

In [40]:
gbm_cls.fit(X_train_cls,y_train_cls)

GradientBoostingClassifier(random_state=42)

In [41]:
gbm_pred_cls = gbm_cls.predict(X_train_cls)

#### Task 16: Implement Gradient Boosting Regresso

In [42]:
gbm_reg = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42)

In [43]:
gbm_reg.fit(X_train_reg,y_train_reg)

GradientBoostingRegressor(random_state=42)

In [44]:
gbm_pred_reg = gbm_reg.predict(X_train_reg)

#### Task 17:Analyze learning rate and number of estimators

The learning rate controls how much each new model contributes to the final prediction. A smaller learning rate makes the model learn slowly but improves generalization, while a larger learning rate speeds up learning but may cause overfitting.

The number of estimators represents the number of boosting stages (trees). More estimators generally improve performance, but too many can lead to overfitting and increased computation time.

There is a trade-off between learning rate and number of estimators: a low learning rate usually requires more estimators, while a high learning rate requires fewer estimators.

### **Light Gradient Boosting (LightGBM)**

In [45]:
from lightgbm import LGBMClassifier, LGBMRegressor

#### Task 18: Implement LightGBM Classifier

In [58]:
lgbm_cls = LGBMClassifier(n_estimators=100,learning_rate=0.05,random_state=42)

In [59]:
lgbm_cls.fit(X_train_cls,y_train_cls)

[LightGBM] [Info] Number of positive: 1559, number of negative: 2601
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000270 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1270
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 15
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.374760 -> initscore=-0.511851
[LightGBM] [Info] Start training from score -0.511851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(learning_rate=0.05, random_state=42)

In [48]:
lgbm_pred_cls = lgbm_cls.predict(X_test_cls)

#### Task 19: Implement LightGBM Regressor

In [56]:
lgbm_reg = LGBMRegressor(n_estimators=200,learning_rate=0.05,random_state=42)

In [57]:
lgbm_reg.fit(X_train_reg,y_train_reg)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001128 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1270
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 15
[LightGBM] [Info] Start training from score 74.774183

LGBMRegressor(learning_rate=0.05, n_estimators=200, random_state=42)

In [51]:
lgbm_pred_reg = lgbm_reg.predict(X_test_reg)

#### Task 20: Analyze performance and training efficiency

LightGBM provides high performance with faster training compared to traditional boosting methods. It uses a histogram-based approach and leaf-wise tree growth, which reduces computation time and improves accuracy.

In this project, LightGBM achieved strong predictive performance while training significantly faster than other boosting models. It efficiently handled large feature sets and reduced overfitting through techniques like regularization.

Overall, LightGBM offers a good balance between speed and accuracy, making it suitable for large-scale machine learning tasks.

### **XGBoost**

In [52]:
from xgboost import XGBClassifier, XGBRegressor

#### Task 21: Implement XGBoost Classifier

In [53]:
xgb_cls = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
)

In [54]:
xgb_cls.fit(X_train_cls,y_train_cls)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [55]:
xgb_pred_cls = xgb_cls.predict(X_test_cls)

#### Task 22: Implement XGBoost Regressor

In [60]:
xgb_reg = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

In [61]:
xgb_reg.fit(X_train_reg,y_train_reg)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [62]:
xgb_pred_reg = xgb_reg.predict(X_test_reg)

#### Task 23: Compare performance and robustness with other boosting models

XGBoost demonstrates superior performance and robustness compared to other boosting algorithms like AdaBoost, Gradient Boosting, and LightGBM. It incorporates regularization techniques (L1 and L2), which help prevent overfitting and improve model generalization.

Compared to AdaBoost, XGBoost is more robust as it handles noise and outliers better. Compared to traditional Gradient Boosting, it is faster and more efficient due to parallel processing and optimized tree construction. While LightGBM is faster in training, XGBoost often provides more stable and consistent results across different datasets.

Overall, XGBoost achieves a strong balance between accuracy, speed, and robustness, making it one of the most reliable boosting algorithms for machine learning tasks.